[project]
name = "rl-drive-taxi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium[classic-control,other]>=1.2.0",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
